
# Stage 1 - Build < -------------------

FROM node AS build

WORKDIR /src

COPY package*.json .
COPY yarn.lock .

RUN yarn install --frozen-lockfile

COPY . .

RUN yarn build


# Stage 2 - Publish < -----------------

FROM nginx AS publish

WORKDIR /usr/share/nginx/html

# Copia o build
RUN rm -rf ./*
COPY --from=build /src/build .

# Arruma o rewrite
RUN rm /etc/nginx/conf.d/default.conf
COPY nginx/nginx.conf /etc/nginx/conf.d

EXPOSE 80

ENTRYPOINT [ "nginx", "-g", "daemon off;" ]